<%@ Page Language="C#" AutoEventWireup="true" CodeFile="dontUseSqldatasource.aspx.cs" Inherits="dontUseSqldatasource" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style>
        .center { margin: auto;

                  width: 50%;

                  border: 3px solid green;

                  padding: 10px; }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <!--<asp:Label ID="FacSSN" runat="server" Text="FacSSN："></asp:Label>
            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacFirstName" runat="server" Text="FacFirstName:"></asp:Label>
            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacLastName" runat="server" Text="FacLastName:"></asp:Label>
            <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacCity" runat="server" Text="FacCity:"></asp:Label>
            <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacState" runat="server" Text="FacState:"></asp:Label>
            <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacDept" runat="server" Text="FacDept:"></asp:Label>
            <asp:TextBox ID="TextBox6" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacRank" runat="server" Text="FacRank:"></asp:Label>
            <asp:TextBox ID="TextBox7" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacSalary" runat="server" Text="FacSalary:"></asp:Label>
            <asp:TextBox ID="TextBox8" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacSupervisor" runat="server" Text="FacSupervisor:"></asp:Label>
            <asp:TextBox ID="TextBox9" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacHireDate" runat="server" Text="FacHireDate:"></asp:Label>
            <asp:TextBox ID="TextBox10" runat="server"></asp:TextBox>
            <br />
            <br />
            <asp:Label ID="FacZipCode" runat="server" Text="FacZipCode:"></asp:Label>
            <asp:TextBox ID="TextBox11" runat="server"></asp:TextBox>
            <br />-->
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Student] WHERE [StdSSN] = ?" InsertCommand="INSERT INTO [Student] ([StdSSN], [StdFirstName], [StdLastName], [StdCity], [StdState], [StdMajor], [StdClass], [StdGPA], [StdZip]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Student]" UpdateCommand="UPDATE [Student] SET [StdFirstName] = ?, [StdLastName] = ?, [StdCity] = ?, [StdState] = ?, [StdMajor] = ?, [StdClass] = ?, [StdGPA] = ?, [StdZip] = ? WHERE [StdSSN] = ?">
                <DeleteParameters>
                    <asp:Parameter Name="StdSSN" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="StdSSN" Type="String" />
                    <asp:Parameter Name="StdFirstName" Type="String" />
                    <asp:Parameter Name="StdLastName" Type="String" />
                    <asp:Parameter Name="StdCity" Type="String" />
                    <asp:Parameter Name="StdState" Type="String" />
                    <asp:Parameter Name="StdMajor" Type="String" />
                    <asp:Parameter Name="StdClass" Type="String" />
                    <asp:Parameter Name="StdGPA" Type="Single" />
                    <asp:Parameter Name="StdZip" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="StdFirstName" Type="String" />
                    <asp:Parameter Name="StdLastName" Type="String" />
                    <asp:Parameter Name="StdCity" Type="String" />
                    <asp:Parameter Name="StdState" Type="String" />
                    <asp:Parameter Name="StdMajor" Type="String" />
                    <asp:Parameter Name="StdClass" Type="String" />
                    <asp:Parameter Name="StdGPA" Type="Single" />
                    <asp:Parameter Name="StdZip" Type="String" />
                    <asp:Parameter Name="StdSSN" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateRows="False" DataKeyNames="StdSSN" DataSourceID="SqlDataSource1" Height="50px" OnItemDeleting="DetailsView1_ItemDeleting" Width="125px">
                <Fields>
                    <asp:BoundField DataField="StdSSN" HeaderText="StdSSN" ReadOnly="True" SortExpression="StdSSN" />
                    <asp:BoundField DataField="StdFirstName" HeaderText="StdFirstName" SortExpression="StdFirstName" />
                    <asp:BoundField DataField="StdLastName" HeaderText="StdLastName" SortExpression="StdLastName" />
                    <asp:BoundField DataField="StdCity" HeaderText="StdCity" SortExpression="StdCity" />
                    <asp:BoundField DataField="StdState" HeaderText="StdState" SortExpression="StdState" />
                    <asp:BoundField DataField="StdMajor" HeaderText="StdMajor" SortExpression="StdMajor" />
                    <asp:BoundField DataField="StdClass" HeaderText="StdClass" SortExpression="StdClass" />
                    <asp:BoundField DataField="StdGPA" HeaderText="StdGPA" SortExpression="StdGPA" />
                    <asp:BoundField DataField="StdZip" HeaderText="StdZip" SortExpression="StdZip" />
                    <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" ShowInsertButton="True" />
                </Fields>
            </asp:DetailsView>
        </div>
    </form>
</body>
</html>
